#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cafe_Otomasyon_Analiz.Islemler
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="Cafe_Otomasyon")]
	public partial class DataBase1DataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertSTOKLAR(STOKLAR instance);
    partial void UpdateSTOKLAR(STOKLAR instance);
    partial void DeleteSTOKLAR(STOKLAR instance);
    partial void InsertURUNLER(URUNLER instance);
    partial void UpdateURUNLER(URUNLER instance);
    partial void DeleteURUNLER(URUNLER instance);
    #endregion
		
		public DataBase1DataContext() : 
				base(global::Cafe_Otomasyon_Analiz.Properties.Settings.Default.Cafe_OtomasyonConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataBase1DataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataBase1DataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataBase1DataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataBase1DataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<STOKLAR> STOKLARs
		{
			get
			{
				return this.GetTable<STOKLAR>();
			}
		}
		
		public System.Data.Linq.Table<URUNLER> URUNLERs
		{
			get
			{
				return this.GetTable<URUNLER>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.STOKLAR")]
	public partial class STOKLAR : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _STOKKODU;
		
		private string _STOKADI;
		
		private string _STOKTURU;
		
		private System.Nullable<System.DateTime> _EKTARIH;
		
		private System.Nullable<System.DateTime> _SONTARIH;
		
		private string _BIRIM;
		
		private string _FIYAT;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnSTOKKODUChanging(string value);
    partial void OnSTOKKODUChanged();
    partial void OnSTOKADIChanging(string value);
    partial void OnSTOKADIChanged();
    partial void OnSTOKTURUChanging(string value);
    partial void OnSTOKTURUChanged();
    partial void OnEKTARIHChanging(System.Nullable<System.DateTime> value);
    partial void OnEKTARIHChanged();
    partial void OnSONTARIHChanging(System.Nullable<System.DateTime> value);
    partial void OnSONTARIHChanged();
    partial void OnBIRIMChanging(string value);
    partial void OnBIRIMChanged();
    partial void OnFIYATChanging(string value);
    partial void OnFIYATChanged();
    #endregion
		
		public STOKLAR()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STOKKODU", DbType="NVarChar(50)")]
		public string STOKKODU
		{
			get
			{
				return this._STOKKODU;
			}
			set
			{
				if ((this._STOKKODU != value))
				{
					this.OnSTOKKODUChanging(value);
					this.SendPropertyChanging();
					this._STOKKODU = value;
					this.SendPropertyChanged("STOKKODU");
					this.OnSTOKKODUChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STOKADI", DbType="NVarChar(50)")]
		public string STOKADI
		{
			get
			{
				return this._STOKADI;
			}
			set
			{
				if ((this._STOKADI != value))
				{
					this.OnSTOKADIChanging(value);
					this.SendPropertyChanging();
					this._STOKADI = value;
					this.SendPropertyChanged("STOKADI");
					this.OnSTOKADIChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STOKTURU", DbType="NVarChar(50)")]
		public string STOKTURU
		{
			get
			{
				return this._STOKTURU;
			}
			set
			{
				if ((this._STOKTURU != value))
				{
					this.OnSTOKTURUChanging(value);
					this.SendPropertyChanging();
					this._STOKTURU = value;
					this.SendPropertyChanged("STOKTURU");
					this.OnSTOKTURUChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EKTARIH", DbType="DateTime")]
		public System.Nullable<System.DateTime> EKTARIH
		{
			get
			{
				return this._EKTARIH;
			}
			set
			{
				if ((this._EKTARIH != value))
				{
					this.OnEKTARIHChanging(value);
					this.SendPropertyChanging();
					this._EKTARIH = value;
					this.SendPropertyChanged("EKTARIH");
					this.OnEKTARIHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SONTARIH", DbType="DateTime")]
		public System.Nullable<System.DateTime> SONTARIH
		{
			get
			{
				return this._SONTARIH;
			}
			set
			{
				if ((this._SONTARIH != value))
				{
					this.OnSONTARIHChanging(value);
					this.SendPropertyChanging();
					this._SONTARIH = value;
					this.SendPropertyChanged("SONTARIH");
					this.OnSONTARIHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BIRIM", DbType="NVarChar(50)")]
		public string BIRIM
		{
			get
			{
				return this._BIRIM;
			}
			set
			{
				if ((this._BIRIM != value))
				{
					this.OnBIRIMChanging(value);
					this.SendPropertyChanging();
					this._BIRIM = value;
					this.SendPropertyChanged("BIRIM");
					this.OnBIRIMChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FIYAT", DbType="NVarChar(50)")]
		public string FIYAT
		{
			get
			{
				return this._FIYAT;
			}
			set
			{
				if ((this._FIYAT != value))
				{
					this.OnFIYATChanging(value);
					this.SendPropertyChanging();
					this._FIYAT = value;
					this.SendPropertyChanged("FIYAT");
					this.OnFIYATChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.URUNLER")]
	public partial class URUNLER : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _URUNADI;
		
		private string _TUR;
		
		private string _RESIM;
		
		private string _FIYAT;
		
		private System.Nullable<System.DateTime> _EKTARIH;
		
		private string _ACIKLAMA;
		
		private System.Nullable<int> _SATISSAYI;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnURUNADIChanging(string value);
    partial void OnURUNADIChanged();
    partial void OnTURChanging(string value);
    partial void OnTURChanged();
    partial void OnRESIMChanging(string value);
    partial void OnRESIMChanged();
    partial void OnFIYATChanging(string value);
    partial void OnFIYATChanged();
    partial void OnEKTARIHChanging(System.Nullable<System.DateTime> value);
    partial void OnEKTARIHChanged();
    partial void OnACIKLAMAChanging(string value);
    partial void OnACIKLAMAChanged();
    partial void OnSATISSAYIChanging(System.Nullable<int> value);
    partial void OnSATISSAYIChanged();
    #endregion
		
		public URUNLER()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_URUNADI", DbType="NVarChar(50)")]
		public string URUNADI
		{
			get
			{
				return this._URUNADI;
			}
			set
			{
				if ((this._URUNADI != value))
				{
					this.OnURUNADIChanging(value);
					this.SendPropertyChanging();
					this._URUNADI = value;
					this.SendPropertyChanged("URUNADI");
					this.OnURUNADIChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TUR", DbType="NVarChar(50)")]
		public string TUR
		{
			get
			{
				return this._TUR;
			}
			set
			{
				if ((this._TUR != value))
				{
					this.OnTURChanging(value);
					this.SendPropertyChanging();
					this._TUR = value;
					this.SendPropertyChanged("TUR");
					this.OnTURChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RESIM", DbType="NVarChar(50)")]
		public string RESIM
		{
			get
			{
				return this._RESIM;
			}
			set
			{
				if ((this._RESIM != value))
				{
					this.OnRESIMChanging(value);
					this.SendPropertyChanging();
					this._RESIM = value;
					this.SendPropertyChanged("RESIM");
					this.OnRESIMChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FIYAT", DbType="NVarChar(50)")]
		public string FIYAT
		{
			get
			{
				return this._FIYAT;
			}
			set
			{
				if ((this._FIYAT != value))
				{
					this.OnFIYATChanging(value);
					this.SendPropertyChanging();
					this._FIYAT = value;
					this.SendPropertyChanged("FIYAT");
					this.OnFIYATChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EKTARIH", DbType="DateTime")]
		public System.Nullable<System.DateTime> EKTARIH
		{
			get
			{
				return this._EKTARIH;
			}
			set
			{
				if ((this._EKTARIH != value))
				{
					this.OnEKTARIHChanging(value);
					this.SendPropertyChanging();
					this._EKTARIH = value;
					this.SendPropertyChanged("EKTARIH");
					this.OnEKTARIHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ACIKLAMA", DbType="NVarChar(50)")]
		public string ACIKLAMA
		{
			get
			{
				return this._ACIKLAMA;
			}
			set
			{
				if ((this._ACIKLAMA != value))
				{
					this.OnACIKLAMAChanging(value);
					this.SendPropertyChanging();
					this._ACIKLAMA = value;
					this.SendPropertyChanged("ACIKLAMA");
					this.OnACIKLAMAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SATISSAYI", DbType="Int")]
		public System.Nullable<int> SATISSAYI
		{
			get
			{
				return this._SATISSAYI;
			}
			set
			{
				if ((this._SATISSAYI != value))
				{
					this.OnSATISSAYIChanging(value);
					this.SendPropertyChanging();
					this._SATISSAYI = value;
					this.SendPropertyChanged("SATISSAYI");
					this.OnSATISSAYIChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
